### ISSUE TITLE
Railroad ags-vector not working

### ISSUE THREAD

**Issue by kgrootendorst** [geomoose/gm3-demo-data#1]
AGS Dakota County Rail layer in the website DEMO (3.3.1-beta ) does not work. When the layer is toggled on, the screen goes blank and the demo stops working altogether.
Attached screen capture is from FireFox inspector.
![capture](https://user-images.githubusercontent.com/36200457/52755930-ac7a2d00-2fcd-11e9-88c6-1696f2a5500d.JPG)

**Comment by theduckylittle** [comment]
I just saw this issue now because we don't usually use this repo for issues with the examples. So it got buried for a YEAR. I think we do have this fixed on the latest version of GeoMoose.

Thanks for reporting!
